### ISSUE TITLE
Automated firewall changes

### ISSUE THREAD

**Issue by murrant** [photinus/ubnt-letsencrypt#3]
Would it be possible to incorporate opening and closing of port 80 for renewals?  (preferably to just letsencrypt ips)

**Comment by photinus** [comment]
Good question. I'll take a look at it.

**Comment by Tim81** [comment]
You could use the following:

sudo iptables -I WAN_LOCAL 1 -p tcp --dport 80 -j ACCEPT
sudo iptables -D WAN_LOCAL 1

First line adds the rule on top of the list, to accept incoming connections on port 80 on all interfaces regardless of source in firewall chain "WAN_LOCAL". All current rules in the chain will go down 1 line, so this rule will be applied before the already existing rules.

Second line will remove the rule on top of the list in chain "WAN_LOCAL" and therefore the firewall is the same as before adding the rule.
